webpackJsonp([8],{

/***/ 387:
/***/ (function(module, exports) {

eval("module.exports = \"<!--\\r\\nAuto-generated\\r\\nDo not edit!!!\\r\\n-->\\r\\n<div class=\\\"kuib-stacked-data-grid\\\">\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\" ng-include=\\\"vm.$model.customSections.top\\\">\\r\\n        </div>\\r\\n    </div>\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\">\\r\\n            <h2 ng-bind-html=\\\"vm.$model.parentTitle\\\"></h2>\\r\\n        </div>\\r\\n    </div>\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\" ng-include=\\\"vm.$model.customSections.topParent\\\">\\r\\n        </div>\\r\\n    </div>\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\">\\r\\n            <grid data-id=\\\"parentGrid\\\" data-options=\\\"vm.$model.parentGridOptions\\\" data-widget=\\\"vm.$parentGrid\\\" data-events=\\\"vm.$model.parentGridEvents\\\"></grid>\\r\\n        </div>\\r\\n    </div>\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\" ng-include=\\\"vm.$model.customSections.middle\\\">\\r\\n        </div>\\r\\n    </div>\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\">\\r\\n            <h2 ng-bind-html=\\\"vm.$model.childTitle\\\"></h2>\\r\\n        </div>\\r\\n    </div>\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\" ng-include=\\\"vm.$model.customSections.topChild\\\">\\r\\n        </div>\\r\\n    </div>\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\">\\r\\n            <grid data-id=\\\"childGrid\\\" data-options=\\\"vm.$model.childGridOptions\\\" data-widget=\\\"vm.$childGrid\\\" data-events=\\\"vm.$model.childGridEvents\\\"></grid>\\r\\n        </div>\\r\\n    </div>\\r\\n    <div class=\\\"row\\\">\\r\\n        <div class=\\\"col-lg-12\\\" ng-include=\\\"vm.$model.customSections.bottom\\\">\\r\\n        </div>\\r\\n    </div>\\r\\n</div>\";\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/modules/contracts/customer-contracts/template.html\n// module id = 387\n// module chunks = 8\n\n//# sourceURL=webpack:///./src/modules/contracts/customer-contracts/template.html?");

/***/ })

});